#include "quickjs-stream.h"
#include "stream-utils.h"
#include "utils.h"
#include <string.h>

/**
 * \defgroup quickjs-stream quickjs-stream: Streams
 * @{
 */

/* ReadableStream/WritableStream/TransformStream and the two queuing-strategy
 * classes are implemented in JS and evaluated here, rather than hand-rolled
 * as C structs/classes. The previous C implementation shared one JSClassID
 * (and repeatedly called JS_SetClassProto on it) across a stream and its
 * controller; each later JS_SetClassProto call frees the previously
 * registered proto, and controller-only prototypes (which nothing else
 * holds a reference to) were dropped to a refcount of 0 and freed while
 * this file's `static JSValue` globals still pointed at them - so
 * `controller.enqueue()` dereferenced freed memory and silently failed
 * (the exception was discarded), and the most basic
 * `new ReadableStream({start(c){c.enqueue(x)}})` + `reader.read()` pattern
 * hung forever. Implementing the state machine in ordinary JS classes
 * sidesteps that whole bug class: real constructors/prototypes, correct
 * `instanceof`, and cycle-safe GC via QuickJS's normal JS object marking
 * (the old code had no `gc_mark` on any of its five classes either). */
static const char js_stream_src[] =
    "(function() {\n"
    "/* Lean WHATWG Streams core: ReadableStream, WritableStream, TransformStream,\n"
    " * CountQueuingStrategy, ByteLengthQueuingStrategy. */\n"
    "\n"
    "function makeDeferred() {\n"
    "  let resolve, reject;\n"
    "  const promise = new Promise((res, rej) => {\n"
    "    resolve = v => {\n"
    "      resolve = () => {};\n"
    "      reject = () => {};\n"
    "      res(v);\n"
    "    };\n"
    "    reject = e => {\n"
    "      resolve = () => {};\n"
    "      reject = () => {};\n"
    "      rej(e);\n"
    "    };\n"
    "  });\n"
    "  return {\n"
    "    promise,\n"
    "    resolve: v => resolve(v),\n"
    "    reject: e => reject(e),\n"
    "  };\n"
    "}\n"
    "\n"
    "/* ==================== ReadableStream ==================== */\n"
    "\n"
    "class ReadableStreamDefaultController {\n"
    "  constructor(stream) {\n"
    "    this._stream = stream;\n"
    "    this._queue = [];\n"
    "    this._queueTotalSize = 0;\n"
    "    this._closeRequested = false;\n"
    "    this._pulling = false;\n"
    "    this._pullAgain = false;\n"
    "  }\n"
    "\n"
    "  get desiredSize() {\n"
    "    const stream = this._stream;\n"
    "    if(stream._state === 'errored') return null;\n"
    "    if(stream._state === 'closed') return 0;\n"
    "    return stream._strategyHWM - this._queueTotalSize;\n"
    "  }\n"
    "\n"
    "  enqueue(chunk) {\n"
    "    const stream = this._stream;\n"
    "    if(!this._canCloseOrEnqueue()) throw new TypeError(\"Cannot enqueue a chunk into a readable stream that is closed or has been requested to be "
    "closed\");\n"
    "\n"
    "    if(stream._reader && stream._reader._readRequests.length > 0) {\n"
    "      const req = stream._reader._readRequests.shift();\n"
    "      req.resolve({ value: chunk, done: false });\n"
    "    } else {\n"
    "      let size = 1;\n"
    "      try {\n"
    "        size = stream._strategySizeAlgorithm(chunk);\n"
    "      } catch(e) {\n"
    "        this.error(e);\n"
    "        throw e;\n"
    "      }\n"
    "      this._queue.push({ value: chunk, size });\n"
    "      this._queueTotalSize += size;\n"
    "    }\n"
    "    this._callPullIfNeeded();\n"
    "  }\n"
    "\n"
    "  close() {\n"
    "    if(!this._canCloseOrEnqueue()) throw new TypeError('Cannot close a readable stream that is already closed or errored');\n"
    "    this._closeRequested = true;\n"
    "    if(this._queue.length === 0) this._finishClose();\n"
    "  }\n"
    "\n"
    "  error(e) {\n"
    "    const stream = this._stream;\n"
    "    if(stream._state !== 'readable') return;\n"
    "    this._queue = [];\n"
    "    this._queueTotalSize = 0;\n"
    "    stream._state = 'errored';\n"
    "    stream._storedError = e;\n"
    "    const reader = stream._reader;\n"
    "    if(reader) {\n"
    "      for(const req of reader._readRequests) req.reject(e);\n"
    "      reader._readRequests = [];\n"
    "      reader._closedPromise.reject(e);\n"
    "    }\n"
    "  }\n"
    "\n"
    "  _canCloseOrEnqueue() {\n"
    "    return !this._closeRequested && this._stream._state === 'readable';\n"
    "  }\n"
    "\n"
    "  _finishClose() {\n"
    "    const stream = this._stream;\n"
    "    stream._state = 'closed';\n"
    "    const reader = stream._reader;\n"
    "    if(reader) {\n"
    "      for(const req of reader._readRequests) req.resolve({ value: undefined, done: true });\n"
    "      reader._readRequests = [];\n"
    "      reader._closedPromise.resolve(undefined);\n"
    "    }\n"
    "  }\n"
    "\n"
    "  _shouldPull() {\n"
    "    const stream = this._stream;\n"
    "    if(stream._state !== 'readable') return false;\n"
    "    if(this._closeRequested) return false;\n"
    "    const size = this.desiredSize;\n"
    "    return size !== null && size > 0;\n"
    "  }\n"
    "\n"
    "  _callPullIfNeeded() {\n"
    "    if(!this._shouldPull()) return;\n"
    "    if(this._pulling) {\n"
    "      this._pullAgain = true;\n"
    "      return;\n"
    "    }\n"
    "    this._pulling = true;\n"
    "    const source = this._stream._underlyingSource;\n"
    "    let result;\n"
    "    try {\n"
    "      result = source.pull ? source.pull(this) : undefined;\n"
    "    } catch(e) {\n"
    "      this._pulling = false;\n"
    "      this.error(e);\n"
    "      return;\n"
    "    }\n"
    "    Promise.resolve(result).then(\n"
    "      () => {\n"
    "        this._pulling = false;\n"
    "        if(this._pullAgain) {\n"
    "          this._pullAgain = false;\n"
    "          this._callPullIfNeeded();\n"
    "        }\n"
    "      },\n"
    "      e => {\n"
    "        this._pulling = false;\n"
    "        this.error(e);\n"
    "      },\n"
    "    );\n"
    "  }\n"
    "}\n"
    "\n"
    "function readableStreamCancel(stream, reason) {\n"
    "  if(stream._state === 'closed') return Promise.resolve(undefined);\n"
    "  if(stream._state === 'errored') return Promise.reject(stream._storedError);\n"
    "\n"
    "  const controller = stream._controller;\n"
    "  controller._queue = [];\n"
    "  controller._queueTotalSize = 0;\n"
    "  stream._state = 'closed';\n"
    "\n"
    "  const reader = stream._reader;\n"
    "  if(reader) {\n"
    "    if(reader._readRequests) {\n"
    "      for(const req of reader._readRequests) req.resolve({ value: undefined, done: true });\n"
    "      reader._readRequests = [];\n"
    "    }\n"
    "    reader._closedPromise.resolve(undefined);\n"
    "  }\n"
    "  if(controller._pendingPullIntos) {\n"
    "    for(const pullInto of controller._pendingPullIntos) pullInto.resolve({ value: viewFromBytes(pullInto.ctor, pullInto.buffer, pullInto.byteOffset, "
    "pullInto.bytesFilled), done: true });\n"
    "    controller._pendingPullIntos = [];\n"
    "  }\n"
    "\n"
    "  const source = stream._underlyingSource;\n"
    "  let result;\n"
    "  try {\n"
    "    result = source.cancel ? source.cancel(reason) : undefined;\n"
    "  } catch(e) {\n"
    "    return Promise.reject(e);\n"
    "  }\n"
    "  return Promise.resolve(result).then(() => undefined);\n"
    "}\n"
    "\n"
    "class ReadableStreamDefaultReader {\n"
    "  constructor(stream) {\n"
    "    if(!(stream instanceof ReadableStream)) throw new TypeError(\"Cannot construct a ReadableStreamDefaultReader from a value that isn't a "
    "ReadableStream\");\n"
    "    if(stream._reader) throw new TypeError('ReadableStream is already locked to a reader');\n"
    "\n"
    "    this._stream = stream;\n"
    "    stream._reader = this;\n"
    "    this._readRequests = [];\n"
    "    this._closedPromise = makeDeferred();\n"
    "\n"
    "    if(stream._state === 'closed') this._closedPromise.resolve(undefined);\n"
    "    else if(stream._state === 'errored') this._closedPromise.reject(stream._storedError);\n"
    "  }\n"
    "\n"
    "  get closed() {\n"
    "    return this._closedPromise.promise;\n"
    "  }\n"
    "\n"
    "  read() {\n"
    "    const stream = this._stream;\n"
    "    if(!stream) return Promise.reject(new TypeError('This readable stream reader has been released and cannot be used to read from its previous owner "
    "stream'));\n"
    "\n"
    "    if(stream._state === 'errored') return Promise.reject(stream._storedError);\n"
    "    if(stream._state === 'closed') return Promise.resolve({ value: undefined, done: true });\n"
    "\n"
    "    const controller = stream._controller;\n"
    "    if(controller._queue.length > 0) {\n"
    "      const { value, size } = controller._queue.shift();\n"
    "      controller._queueTotalSize -= size;\n"
    "      if(controller._closeRequested && controller._queue.length === 0) controller._finishClose();\n"
    "      else controller._callPullIfNeeded();\n"
    "      return Promise.resolve({ value, done: false });\n"
    "    }\n"
    "\n"
    "    const d = makeDeferred();\n"
    "    this._readRequests.push(d);\n"
    "    controller._callPullIfNeeded();\n"
    "    return d.promise;\n"
    "  }\n"
    "\n"
    "  cancel(reason) {\n"
    "    const stream = this._stream;\n"
    "    if(!stream) return Promise.reject(new TypeError('This readable stream reader has been released'));\n"
    "    return readableStreamCancel(stream, reason);\n"
    "  }\n"
    "\n"
    "  releaseLock() {\n"
    "    const stream = this._stream;\n"
    "    if(!stream) return;\n"
    "    if(this._readRequests.length > 0) {\n"
    "      const e = new TypeError('Reader was released');\n"
    "      for(const req of this._readRequests) req.reject(e);\n"
    "      this._readRequests = [];\n"
    "    }\n"
    "    stream._reader = undefined;\n"
    "    this._stream = undefined;\n"
    "  }\n"
    "}\n"
    "\n"
    "/* ==================== ReadableByteStreamController / BYOB ==================== */\n"
    "\n"
    "function viewFromBytes(ctor, buffer, byteOffset, byteLength) {\n"
    "  if(ctor === DataView) return new DataView(buffer, byteOffset, byteLength);\n"
    "  const bpe = ctor.BYTES_PER_ELEMENT || 1;\n"
    "  return new ctor(buffer, byteOffset, byteLength / bpe);\n"
    "}\n"
    "\n"
    "class ReadableStreamBYOBRequest {\n"
    "  constructor(controller, view) {\n"
    "    this._controller = controller;\n"
    "    this._view = view;\n"
    "  }\n"
    "\n"
    "  get view() {\n"
    "    return this._view;\n"
    "  }\n"
    "\n"
    "  respond(bytesWritten) {\n"
    "    this._controller._respond(bytesWritten);\n"
    "  }\n"
    "\n"
    "  respondWithNewView(view) {\n"
    "    this._controller._respondWithNewView(view);\n"
    "  }\n"
    "}\n"
    "\n"
    "class ReadableByteStreamController {\n"
    "  constructor(stream, autoAllocateChunkSize) {\n"
    "    this._stream = stream;\n"
    "    this._queue = [];\n"
    "    this._queueTotalSize = 0;\n"
    "    this._closeRequested = false;\n"
    "    this._pulling = false;\n"
    "    this._pullAgain = false;\n"
    "    this._autoAllocateChunkSize = autoAllocateChunkSize;\n"
    "    this._pendingPullIntos = [];\n"
    "    this._byobRequest = null;\n"
    "  }\n"
    "\n"
    "  get desiredSize() {\n"
    "    const stream = this._stream;\n"
    "    if(stream._state === 'errored') return null;\n"
    "    if(stream._state === 'closed') return 0;\n"
    "    return stream._strategyHWM - this._queueTotalSize;\n"
    "  }\n"
    "\n"
    "  get byobRequest() {\n"
    "    if(this._byobRequest === null && this._pendingPullIntos.length > 0) {\n"
    "      const pullInto = this._pendingPullIntos[0];\n"
    "      const view = new Uint8Array(pullInto.buffer, pullInto.byteOffset + pullInto.bytesFilled, pullInto.byteLength - pullInto.bytesFilled);\n"
    "      this._byobRequest = new ReadableStreamBYOBRequest(this, view);\n"
    "    }\n"
    "    return this._byobRequest;\n"
    "  }\n"
    "\n"
    "  enqueue(chunk) {\n"
    "    const stream = this._stream;\n"
    "    if(!this._canCloseOrEnqueue()) throw new TypeError('Cannot enqueue a chunk into a readable stream that is closed or has been requested to be "
    "closed');\n"
    "    if(!ArrayBuffer.isView(chunk)) throw new TypeError('chunk must be an ArrayBufferView (e.g. Uint8Array)');\n"
    "\n"
    "    const bytes = new Uint8Array(chunk.buffer, chunk.byteOffset, chunk.byteLength);\n"
    "\n"
    "    if(this._pendingPullIntos.length > 0) {\n"
    "      this._fillPendingFromBytes(bytes);\n"
    "    } else if(stream._reader && stream._reader._readRequests && stream._reader._readRequests.length > 0) {\n"
    "      const req = stream._reader._readRequests.shift();\n"
    "      req.resolve({ value: bytes, done: false });\n"
    "    } else {\n"
    "      this._queue.push({ value: bytes, size: bytes.byteLength });\n"
    "      this._queueTotalSize += bytes.byteLength;\n"
    "    }\n"
    "    this._callPullIfNeeded();\n"
    "  }\n"
    "\n"
    "  close() {\n"
    "    if(!this._canCloseOrEnqueue()) throw new TypeError('Cannot close a readable stream that is already closed or errored');\n"
    "    this._closeRequested = true;\n"
    "\n"
    "    if(this._queueTotalSize > 0) return;\n"
    "\n"
    "    if(this._pendingPullIntos.length > 0 && this._pendingPullIntos[0].bytesFilled > 0) {\n"
    "      const e = new TypeError('Insufficient bytes to fill elements requested in a ReadableStream BYOB read');\n"
    "      this.error(e);\n"
    "      throw e;\n"
    "    }\n"
    "    this._finishClose();\n"
    "  }\n"
    "\n"
    "  error(e) {\n"
    "    const stream = this._stream;\n"
    "    if(stream._state !== 'readable') return;\n"
    "    this._queue = [];\n"
    "    this._queueTotalSize = 0;\n"
    "    stream._state = 'errored';\n"
    "    stream._storedError = e;\n"
    "    const reader = stream._reader;\n"
    "    if(reader) {\n"
    "      if(reader._readRequests) {\n"
    "        for(const req of reader._readRequests) req.reject(e);\n"
    "        reader._readRequests = [];\n"
    "      }\n"
    "      reader._closedPromise.reject(e);\n"
    "    }\n"
    "    for(const pullInto of this._pendingPullIntos) pullInto.reject(e);\n"
    "    this._pendingPullIntos = [];\n"
    "  }\n"
    "\n"
    "  _canCloseOrEnqueue() {\n"
    "    return !this._closeRequested && this._stream._state === 'readable';\n"
    "  }\n"
    "\n"
    "  _finishClose() {\n"
    "    const stream = this._stream;\n"
    "    stream._state = 'closed';\n"
    "    const reader = stream._reader;\n"
    "    if(reader) {\n"
    "      if(reader._readRequests) {\n"
    "        for(const req of reader._readRequests) req.resolve({ value: undefined, done: true });\n"
    "        reader._readRequests = [];\n"
    "      }\n"
    "      reader._closedPromise.resolve(undefined);\n"
    "    }\n"
    "    for(const pullInto of this._pendingPullIntos) pullInto.resolve({ value: viewFromBytes(pullInto.ctor, pullInto.buffer, pullInto.byteOffset, "
    "pullInto.bytesFilled), done: true });\n"
    "    this._pendingPullIntos = [];\n"
    "  }\n"
    "\n"
    "  _shouldPull() {\n"
    "    const stream = this._stream;\n"
    "    if(stream._state !== 'readable') return false;\n"
    "    if(this._closeRequested) return false;\n"
    "    if(this._pendingPullIntos.length > 0) return true;\n"
    "    if(this._autoAllocateChunkSize && stream._reader && stream._reader._readRequests && stream._reader._readRequests.length > 0) return true;\n"
    "    const size = this.desiredSize;\n"
    "    return size !== null && size > 0;\n"
    "  }\n"
    "\n"
    "  _callPullIfNeeded() {\n"
    "    if(!this._shouldPull()) return;\n"
    "    if(this._pulling) {\n"
    "      this._pullAgain = true;\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    if(this._pendingPullIntos.length === 0 && this._autoAllocateChunkSize) {\n"
    "      const buffer = new ArrayBuffer(this._autoAllocateChunkSize);\n"
    "      this._pendingPullIntos.push({\n"
    "        buffer,\n"
    "        byteOffset: 0,\n"
    "        byteLength: this._autoAllocateChunkSize,\n"
    "        bytesFilled: 0,\n"
    "        ctor: Uint8Array,\n"
    "        resolve: result => this._deliverAutoAllocated(result),\n"
    "        reject: e => this.error(e),\n"
    "      });\n"
    "    }\n"
    "\n"
    "    this._pulling = true;\n"
    "    const source = this._stream._underlyingSource;\n"
    "    let result;\n"
    "    try {\n"
    "      result = source.pull ? source.pull(this) : undefined;\n"
    "    } catch(e) {\n"
    "      this._pulling = false;\n"
    "      this.error(e);\n"
    "      return;\n"
    "    }\n"
    "    Promise.resolve(result).then(\n"
    "      () => {\n"
    "        this._pulling = false;\n"
    "        if(this._pullAgain) {\n"
    "          this._pullAgain = false;\n"
    "          this._callPullIfNeeded();\n"
    "        }\n"
    "      },\n"
    "      e => {\n"
    "        this._pulling = false;\n"
    "        this.error(e);\n"
    "      },\n"
    "    );\n"
    "  }\n"
    "\n"
    "  _deliverAutoAllocated({ value, done }) {\n"
    "    if(done) return;\n"
    "    const stream = this._stream;\n"
    "    if(stream._reader && stream._reader._readRequests && stream._reader._readRequests.length > 0) {\n"
    "      const req = stream._reader._readRequests.shift();\n"
    "      req.resolve({ value, done: false });\n"
    "    } else {\n"
    "      this._queue.push({ value, size: value.byteLength });\n"
    "      this._queueTotalSize += value.byteLength;\n"
    "    }\n"
    "  }\n"
    "\n"
    "  _fillViewFromQueue(view) {\n"
    "    const dest = new Uint8Array(view.buffer, view.byteOffset, view.byteLength);\n"
    "    let filled = 0;\n"
    "\n"
    "    while(filled < dest.length && this._queue.length > 0) {\n"
    "      const entry = this._queue[0];\n"
    "      const src = entry.value;\n"
    "      const toCopy = Math.min(dest.length - filled, src.byteLength);\n"
    "\n"
    "      dest.set(src.subarray(0, toCopy), filled);\n"
    "      filled += toCopy;\n"
    "\n"
    "      if(toCopy >= src.byteLength) {\n"
    "        this._queue.shift();\n"
    "        this._queueTotalSize -= entry.size;\n"
    "      } else {\n"
    "        entry.value = src.subarray(toCopy);\n"
    "        entry.size -= toCopy;\n"
    "        this._queueTotalSize -= toCopy;\n"
    "      }\n"
    "    }\n"
    "\n"
    "    if(this._closeRequested && this._queue.length === 0) this._finishClose();\n"
    "    else this._callPullIfNeeded();\n"
    "\n"
    "    return { value: viewFromBytes(view.constructor, view.buffer, view.byteOffset, filled), done: false };\n"
    "  }\n"
    "\n"
    "  _fillPendingFromBytes(bytes) {\n"
    "    let offset = 0;\n"
    "\n"
    "    while(this._pendingPullIntos.length > 0 && offset < bytes.byteLength) {\n"
    "      const pullInto = this._pendingPullIntos[0];\n"
    "      const destRemaining = pullInto.byteLength - pullInto.bytesFilled;\n"
    "      const toCopy = Math.min(destRemaining, bytes.byteLength - offset);\n"
    "\n"
    "      new Uint8Array(pullInto.buffer, pullInto.byteOffset + pullInto.bytesFilled, toCopy).set(bytes.subarray(offset, offset + toCopy));\n"
    "      pullInto.bytesFilled += toCopy;\n"
    "      offset += toCopy;\n"
    "\n"
    "      if(pullInto.bytesFilled >= pullInto.byteLength) {\n"
    "        this._pendingPullIntos.shift();\n"
    "        this._byobRequest = null;\n"
    "        pullInto.resolve({ value: viewFromBytes(pullInto.ctor, pullInto.buffer, pullInto.byteOffset, pullInto.bytesFilled), done: false });\n"
    "      } else {\n"
    "        break;\n"
    "      }\n"
    "    }\n"
    "\n"
    "    if(offset < bytes.byteLength) {\n"
    "      const rest = bytes.subarray(offset);\n"
    "      this._queue.push({ value: rest, size: rest.byteLength });\n"
    "      this._queueTotalSize += rest.byteLength;\n"
    "    }\n"
    "  }\n"
    "\n"
    "  _respond(bytesWritten) {\n"
    "    if(this._pendingPullIntos.length === 0) throw new TypeError('No pending BYOB read request to respond to');\n"
    "    const pullInto = this._pendingPullIntos[0];\n"
    "    this._byobRequest = null;\n"
    "    pullInto.bytesFilled += bytesWritten;\n"
    "\n"
    "    if(bytesWritten === 0 && this._closeRequested) {\n"
    "      this._pendingPullIntos.shift();\n"
    "      pullInto.resolve({ value: viewFromBytes(pullInto.ctor, pullInto.buffer, pullInto.byteOffset, pullInto.bytesFilled), done: true });\n"
    "      if(this._pendingPullIntos.length === 0) this._finishClose();\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    if(pullInto.bytesFilled > 0 || bytesWritten > 0) {\n"
    "      this._pendingPullIntos.shift();\n"
    "      pullInto.resolve({ value: viewFromBytes(pullInto.ctor, pullInto.buffer, pullInto.byteOffset, pullInto.bytesFilled), done: false });\n"
    "    }\n"
    "  }\n"
    "\n"
    "  _respondWithNewView(view) {\n"
    "    if(this._pendingPullIntos.length === 0) throw new TypeError('No pending BYOB read request to respond to');\n"
    "    const pullInto = this._pendingPullIntos.shift();\n"
    "    this._byobRequest = null;\n"
    "    pullInto.resolve({ value: view, done: false });\n"
    "  }\n"
    "}\n"
    "\n"
    "class ReadableStreamBYOBReader {\n"
    "  constructor(stream) {\n"
    "    if(!(stream instanceof ReadableStream)) throw new TypeError(\"Cannot construct a ReadableStreamBYOBReader from a value that isn't a "
    "ReadableStream\");\n"
    "    if(!(stream._controller instanceof ReadableByteStreamController))\n"
    "      throw new TypeError('Cannot construct a ReadableStreamBYOBReader for a stream not constructed with {type: \"bytes\"}');\n"
    "    if(stream._reader) throw new TypeError('ReadableStream is already locked to a reader');\n"
    "\n"
    "    this._stream = stream;\n"
    "    stream._reader = this;\n"
    "    this._closedPromise = makeDeferred();\n"
    "\n"
    "    if(stream._state === 'closed') this._closedPromise.resolve(undefined);\n"
    "    else if(stream._state === 'errored') this._closedPromise.reject(stream._storedError);\n"
    "  }\n"
    "\n"
    "  get closed() {\n"
    "    return this._closedPromise.promise;\n"
    "  }\n"
    "\n"
    "  read(view) {\n"
    "    const stream = this._stream;\n"
    "    if(!stream) return Promise.reject(new TypeError('This readable stream BYOB reader has been released'));\n"
    "    if(!ArrayBuffer.isView(view) || view.byteLength === 0) return Promise.reject(new TypeError('read(view) requires a non-empty ArrayBufferView'));\n"
    "    if(stream._state === 'errored') return Promise.reject(stream._storedError);\n"
    "\n"
    "    const controller = stream._controller;\n"
    "\n"
    "    if(controller._queueTotalSize > 0) return Promise.resolve(controller._fillViewFromQueue(view));\n"
    "\n"
    "    if(stream._state === 'closed') return Promise.resolve({ value: viewFromBytes(view.constructor, view.buffer, view.byteOffset, 0), done: true });\n"
    "\n"
    "    const d = makeDeferred();\n"
    "    controller._pendingPullIntos.push({\n"
    "      buffer: view.buffer,\n"
    "      byteOffset: view.byteOffset,\n"
    "      byteLength: view.byteLength,\n"
    "      bytesFilled: 0,\n"
    "      ctor: view.constructor,\n"
    "      resolve: d.resolve,\n"
    "      reject: d.reject,\n"
    "    });\n"
    "    controller._callPullIfNeeded();\n"
    "    return d.promise;\n"
    "  }\n"
    "\n"
    "  cancel(reason) {\n"
    "    const stream = this._stream;\n"
    "    if(!stream) return Promise.reject(new TypeError('This readable stream BYOB reader has been released'));\n"
    "    return readableStreamCancel(stream, reason);\n"
    "  }\n"
    "\n"
    "  releaseLock() {\n"
    "    const stream = this._stream;\n"
    "    if(!stream) return;\n"
    "    const controller = stream._controller;\n"
    "    if(controller._pendingPullIntos.length > 0) {\n"
    "      const e = new TypeError('Reader was released');\n"
    "      for(const p of controller._pendingPullIntos) p.reject(e);\n"
    "      controller._pendingPullIntos = [];\n"
    "    }\n"
    "    stream._reader = undefined;\n"
    "    this._stream = undefined;\n"
    "  }\n"
    "}\n"
    "\n"
    "function readableStreamAsyncIterator(stream, { preventCancel = false } = {}) {\n"
    "  const reader = stream.getReader();\n"
    "  return {\n"
    "    next() {\n"
    "      return reader.read().then(({ value, done }) => {\n"
    "        if(done) reader.releaseLock();\n"
    "        return { value, done };\n"
    "      });\n"
    "    },\n"
    "    return(value) {\n"
    "      const finish = () => {\n"
    "        reader.releaseLock();\n"
    "        return { value, done: true };\n"
    "      };\n"
    "      if(preventCancel) return Promise.resolve(finish());\n"
    "      return reader.cancel().then(finish, finish);\n"
    "    },\n"
    "    [Symbol.asyncIterator]() {\n"
    "      return this;\n"
    "    },\n"
    "  };\n"
    "}\n"
    "\n"
    "class ReadableStream {\n"
    "  constructor(underlyingSource = {}, strategy = {}) {\n"
    "    const isBytes = underlyingSource.type === 'bytes';\n"
    "\n"
    "    this._state = 'readable';\n"
    "    this._storedError = undefined;\n"
    "    this._reader = undefined;\n"
    "    this._underlyingSource = underlyingSource;\n"
    "    this._strategyHWM = strategy.highWaterMark ?? (isBytes ? 0 : 1);\n"
    "    this._strategySizeAlgorithm = strategy.size ?? (() => 1);\n"
    "    this._controller = isBytes ? new ReadableByteStreamController(this, underlyingSource.autoAllocateChunkSize) : new "
    "ReadableStreamDefaultController(this);\n"
    "\n"
    "    const startResult = underlyingSource.start ? underlyingSource.start(this._controller) : undefined;\n"
    "\n"
    "    Promise.resolve(startResult).then(\n"
    "      () => this._controller._callPullIfNeeded(),\n"
    "      e => this._controller.error(e),\n"
    "    );\n"
    "  }\n"
    "\n"
    "  get locked() {\n"
    "    return !!this._reader;\n"
    "  }\n"
    "\n"
    "  getReader(options = {}) {\n"
    "    if(options.mode === 'byob') return new ReadableStreamBYOBReader(this);\n"
    "    return new ReadableStreamDefaultReader(this);\n"
    "  }\n"
    "\n"
    "  cancel(reason) {\n"
    "    if(this._reader) return Promise.reject(new TypeError('Cannot cancel a readable stream that is locked to a reader'));\n"
    "    return readableStreamCancel(this, reason);\n"
    "  }\n"
    "\n"
    "  [Symbol.asyncIterator](options) {\n"
    "    return readableStreamAsyncIterator(this, options);\n"
    "  }\n"
    "}\n"
    "\n"
    "/* ==================== WritableStream ==================== */\n"
    "\n"
    "class WritableStreamDefaultController {\n"
    "  constructor(stream) {\n"
    "    this._stream = stream;\n"
    "  }\n"
    "\n"
    "  error(e) {\n"
    "    this._stream._error(e);\n"
    "  }\n"
    "}\n"
    "\n"
    "class WritableStreamDefaultWriter {\n"
    "  constructor(stream) {\n"
    "    if(!(stream instanceof WritableStream)) throw new TypeError(\"Cannot construct a WritableStreamDefaultWriter from a value that isn't a "
    "WritableStream\");\n"
    "    if(stream._writer) throw new TypeError('WritableStream is already locked to a writer');\n"
    "\n"
    "    this._stream = stream;\n"
    "    stream._writer = this;\n"
    "\n"
    "    this._closedPromise = makeDeferred();\n"
    "    this._readyPromise = makeDeferred();\n"
    "\n"
    "    if(stream._state === 'errored') this._closedPromise.reject(stream._storedError);\n"
    "    else if(stream._state === 'closed') this._closedPromise.resolve(undefined);\n"
    "\n"
    "    if(!stream._backpressure) this._readyPromise.resolve(undefined);\n"
    "  }\n"
    "\n"
    "  get closed() {\n"
    "    return this._closedPromise.promise;\n"
    "  }\n"
    "\n"
    "  get ready() {\n"
    "    return this._readyPromise.promise;\n"
    "  }\n"
    "\n"
    "  get desiredSize() {\n"
    "    const stream = this._stream;\n"
    "    if(stream._state === 'errored') return null;\n"
    "    if(stream._state === 'closed') return 0;\n"
    "    return stream._strategyHWM - stream._queueTotalSize;\n"
    "  }\n"
    "\n"
    "  write(chunk) {\n"
    "    const stream = this._stream;\n"
    "    if(!stream) return Promise.reject(new TypeError('This writable stream writer has been released'));\n"
    "    return writableStreamWrite(stream, chunk);\n"
    "  }\n"
    "\n"
    "  close() {\n"
    "    const stream = this._stream;\n"
    "    if(!stream) return Promise.reject(new TypeError('This writable stream writer has been released'));\n"
    "    return writableStreamClose(stream);\n"
    "  }\n"
    "\n"
    "  abort(reason) {\n"
    "    const stream = this._stream;\n"
    "    if(!stream) return Promise.reject(new TypeError('This writable stream writer has been released'));\n"
    "    return writableStreamAbort(stream, reason);\n"
    "  }\n"
    "\n"
    "  releaseLock() {\n"
    "    const stream = this._stream;\n"
    "    if(!stream) return;\n"
    "    stream._writer = undefined;\n"
    "    this._stream = undefined;\n"
    "  }\n"
    "}\n"
    "\n"
    "function writableStreamWrite(stream, chunk) {\n"
    "  if(stream._state === 'errored') return Promise.reject(stream._storedError);\n"
    "  if(stream._state === 'closed' || stream._closeRequested) return Promise.reject(new TypeError('The stream is closing or closed and cannot be written "
    "to'));\n"
    "\n"
    "  let size = 1;\n"
    "  try {\n"
    "    size = stream._strategySizeAlgorithm(chunk);\n"
    "  } catch(e) {\n"
    "    stream._error(e);\n"
    "    return Promise.reject(e);\n"
    "  }\n"
    "\n"
    "  const d = makeDeferred();\n"
    "  stream._queue.push({ type: 'chunk', chunk, size, resolve: d.resolve, reject: d.reject });\n"
    "  stream._queueTotalSize += size;\n"
    "  stream._checkBackpressure();\n"
    "  stream._advanceQueue();\n"
    "  return d.promise;\n"
    "}\n"
    "\n"
    "function writableStreamClose(stream) {\n"
    "  if(stream._state === 'errored') return Promise.reject(stream._storedError);\n"
    "  if(stream._closeRequested || stream._state === 'closed') return Promise.reject(new TypeError('Cannot close an already-closing or closed writable "
    "stream'));\n"
    "\n"
    "  stream._closeRequested = true;\n"
    "  const d = makeDeferred();\n"
    "  stream._queue.push({ type: 'close', resolve: d.resolve, reject: d.reject });\n"
    "  stream._advanceQueue();\n"
    "  return d.promise;\n"
    "}\n"
    "\n"
    "function writableStreamAbort(stream, reason) {\n"
    "  if(stream._state === 'errored' || stream._state === 'closed') return Promise.resolve(undefined);\n"
    "\n"
    "  const source = stream._underlyingSink;\n"
    "  stream._error(reason);\n"
    "\n"
    "  let result;\n"
    "  try {\n"
    "    result = source.abort ? source.abort(reason) : undefined;\n"
    "  } catch(e) {\n"
    "    return Promise.reject(e);\n"
    "  }\n"
    "  return Promise.resolve(result).then(() => undefined);\n"
    "}\n"
    "\n"
    "class WritableStream {\n"
    "  constructor(underlyingSink = {}, strategy = {}) {\n"
    "    this._state = 'writable';\n"
    "    this._storedError = undefined;\n"
    "    this._writer = undefined;\n"
    "    this._underlyingSink = underlyingSink;\n"
    "    this._strategyHWM = strategy.highWaterMark ?? 1;\n"
    "    this._strategySizeAlgorithm = strategy.size ?? (() => 1);\n"
    "    this._queue = [];\n"
    "    this._queueTotalSize = 0;\n"
    "    this._writing = false;\n"
    "    this._closeRequested = false;\n"
    "    this._backpressure = false;\n"
    "    this._controller = new WritableStreamDefaultController(this);\n"
    "\n"
    "    const startResult = underlyingSink.start ? underlyingSink.start(this._controller) : undefined;\n"
    "    Promise.resolve(startResult).then(\n"
    "      () => this._advanceQueue(),\n"
    "      e => this._error(e),\n"
    "    );\n"
    "  }\n"
    "\n"
    "  get locked() {\n"
    "    return !!this._writer;\n"
    "  }\n"
    "\n"
    "  getWriter() {\n"
    "    return new WritableStreamDefaultWriter(this);\n"
    "  }\n"
    "\n"
    "  close() {\n"
    "    if(this._writer) return Promise.reject(new TypeError('Cannot close a writable stream that is locked to a writer'));\n"
    "    return writableStreamClose(this);\n"
    "  }\n"
    "\n"
    "  abort(reason) {\n"
    "    if(this._writer) return Promise.reject(new TypeError('Cannot abort a writable stream that is locked to a writer'));\n"
    "    return writableStreamAbort(this, reason);\n"
    "  }\n"
    "\n"
    "  _checkBackpressure() {\n"
    "    const bp = this._strategyHWM - this._queueTotalSize <= 0;\n"
    "    if(bp === this._backpressure) return;\n"
    "    this._backpressure = bp;\n"
    "    const writer = this._writer;\n"
    "    if(!writer) return;\n"
    "    if(bp) writer._readyPromise = makeDeferred();\n"
    "    else writer._readyPromise.resolve(undefined);\n"
    "  }\n"
    "\n"
    "  _advanceQueue() {\n"
    "    if(this._writing) return;\n"
    "    if(this._queue.length === 0) return;\n"
    "    if(this._state !== 'writable') return;\n"
    "\n"
    "    const entry = this._queue[0];\n"
    "    const sink = this._underlyingSink;\n"
    "    this._writing = true;\n"
    "\n"
    "    if(entry.type === 'close') {\n"
    "      let result;\n"
    "      try {\n"
    "        result = sink.close ? sink.close() : undefined;\n"
    "      } catch(e) {\n"
    "        this._writing = false;\n"
    "        this._queue.shift();\n"
    "        entry.reject(e);\n"
    "        this._error(e);\n"
    "        return;\n"
    "      }\n"
    "      Promise.resolve(result).then(\n"
    "        () => {\n"
    "          this._writing = false;\n"
    "          this._queue.shift();\n"
    "          this._state = 'closed';\n"
    "          entry.resolve(undefined);\n"
    "          if(this._writer) this._writer._closedPromise.resolve(undefined);\n"
    "        },\n"
    "        e => {\n"
    "          this._writing = false;\n"
    "          this._queue.shift();\n"
    "          entry.reject(e);\n"
    "          this._error(e);\n"
    "        },\n"
    "      );\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    let result;\n"
    "    try {\n"
    "      result = sink.write ? sink.write(entry.chunk, this._controller) : undefined;\n"
    "    } catch(e) {\n"
    "      this._writing = false;\n"
    "      this._queue.shift();\n"
    "      this._queueTotalSize -= entry.size;\n"
    "      entry.reject(e);\n"
    "      this._error(e);\n"
    "      return;\n"
    "    }\n"
    "    Promise.resolve(result).then(\n"
    "      () => {\n"
    "        this._writing = false;\n"
    "        this._queue.shift();\n"
    "        this._queueTotalSize -= entry.size;\n"
    "        entry.resolve(undefined);\n"
    "        this._checkBackpressure();\n"
    "        this._advanceQueue();\n"
    "      },\n"
    "      e => {\n"
    "        this._writing = false;\n"
    "        this._queue.shift();\n"
    "        this._queueTotalSize -= entry.size;\n"
    "        entry.reject(e);\n"
    "        this._error(e);\n"
    "      },\n"
    "    );\n"
    "  }\n"
    "\n"
    "  _error(e) {\n"
    "    if(this._state === 'errored' || this._state === 'closed') return;\n"
    "    this._state = 'errored';\n"
    "    this._storedError = e;\n"
    "\n"
    "    for(const entry of this._queue) entry.reject(e);\n"
    "    this._queue = [];\n"
    "    this._queueTotalSize = 0;\n"
    "\n"
    "    const writer = this._writer;\n"
    "    if(writer) {\n"
    "      writer._closedPromise.reject(e);\n"
    "      writer._readyPromise.reject(e);\n"
    "    }\n"
    "  }\n"
    "}\n"
    "\n"
    "/* ==================== TransformStream ==================== */\n"
    "\n"
    "class TransformStreamDefaultController {\n"
    "  get desiredSize() {\n"
    "    return this._readableController.desiredSize;\n"
    "  }\n"
    "\n"
    "  enqueue(chunk) {\n"
    "    this._readableController.enqueue(chunk);\n"
    "  }\n"
    "\n"
    "  error(e) {\n"
    "    this._readableController.error(e);\n"
    "  }\n"
    "\n"
    "  terminate() {\n"
    "    this._readableController.close();\n"
    "  }\n"
    "}\n"
    "\n"
    "class TransformStream {\n"
    "  constructor(transformer = {}, writableStrategy = {}, readableStrategy = {}) {\n"
    "    const controller = new TransformStreamDefaultController();\n"
    "\n"
    "    let readableController;\n"
    "    const readable = new ReadableStream(\n"
    "      {\n"
    "        start(c) {\n"
    "          readableController = c;\n"
    "        },\n"
    "      },\n"
    "      readableStrategy,\n"
    "    );\n"
    "    controller._readableController = readableController;\n"
    "\n"
    "    const transformAlgorithm = transformer.transform ? chunk => transformer.transform(chunk, controller) : chunk => controller.enqueue(chunk);\n"
    "\n"
    "    const writable = new WritableStream(\n"
    "      {\n"
    "        write(chunk) {\n"
    "          try {\n"
    "            return Promise.resolve(transformAlgorithm(chunk)).catch(e => {\n"
    "              controller.error(e);\n"
    "              throw e;\n"
    "            });\n"
    "          } catch(e) {\n"
    "            controller.error(e);\n"
    "            throw e;\n"
    "          }\n"
    "        },\n"
    "        close() {\n"
    "          const flushResult = transformer.flush ? transformer.flush(controller) : undefined;\n"
    "          return Promise.resolve(flushResult).then(\n"
    "            () => readableController.close(),\n"
    "            e => {\n"
    "              controller.error(e);\n"
    "              throw e;\n"
    "            },\n"
    "          );\n"
    "        },\n"
    "        abort(reason) {\n"
    "          controller.error(reason);\n"
    "        },\n"
    "      },\n"
    "      writableStrategy,\n"
    "    );\n"
    "\n"
    "    this.readable = readable;\n"
    "    this.writable = writable;\n"
    "    this._controller = controller;\n"
    "  }\n"
    "}\n"
    "\n"
    "/* ==================== queuing strategies ==================== */\n"
    "\n"
    "class CountQueuingStrategy {\n"
    "  constructor(init) {\n"
    "    this.highWaterMark = init.highWaterMark;\n"
    "  }\n"
    "  size() {\n"
    "    return 1;\n"
    "  }\n"
    "}\n"
    "\n"
    "class ByteLengthQueuingStrategy {\n"
    "  constructor(init) {\n"
    "    this.highWaterMark = init.highWaterMark;\n"
    "  }\n"
    "  size(chunk) {\n"
    "    return chunk.byteLength;\n"
    "  }\n"
    "}\n"
    "\n"
    "  return { ReadableStream, WritableStream, TransformStream, CountQueuingStrategy, ByteLengthQueuingStrategy };\n"
    "})\n";

/* Persisted after js_stream_init evaluates the JS factory, so other C code
 * (via js_readable_stream_from_reader) and js_readable_stream_from_reader_ctor
 * (the JS-visible ReadableStream.fromReader()) can construct instances without
 * re-evaluating the script. */
static JSValue readable_stream_ctor = JS_UNDEFINED;

typedef struct {
  Reader reader;
  size_t chunk_size;
} ReaderSource;

static void
reader_source_finalizer(JSRuntime* rt, void* opaque) {
  ReaderSource* rs = opaque;

  reader_free(&rs->reader);
  js_free_rt(rt, rs);
}

static void
reader_source_buffer_free(JSRuntime* rt, void* opaque, void* ptr) {
  js_free_rt(rt, ptr);
}

/* pull(controller): reads up to chunk_size bytes from the wrapped Reader into
 * a fresh ArrayBuffer and enqueues it, or closes the stream on EOF (a 0
 * return from reader_read). */
static JSValue
reader_source_pull(JSContext* ctx, JSValueConst this_val, int argc, JSValueConst argv[], int magic, void* opaque) {
  ReaderSource* rs = opaque;
  JSValueConst controller = argc > 0 ? argv[0] : JS_UNDEFINED;
  JSValue fn, ret, chunk, buffer;
  uint8_t* buf;
  ssize_t n;

  if(!(buf = js_malloc(ctx, rs->chunk_size)))
    return JS_EXCEPTION;

  n = reader_read(&rs->reader, buf, rs->chunk_size);

  if(n < 0) {
    js_free(ctx, buf);
    return JS_ThrowInternalError(ctx, "ReadableStream.fromReader(): read error");
  }

  if(n == 0) {
    js_free(ctx, buf);
    fn = JS_GetPropertyStr(ctx, controller, "close");
    ret = JS_Call(ctx, fn, controller, 0, 0);
    JS_FreeValue(ctx, fn);
    return ret;
  }

  buffer = JS_NewArrayBuffer(ctx, buf, n, reader_source_buffer_free, NULL, FALSE);
  chunk = js_typedarray_new(ctx, 8, FALSE, FALSE, buffer);
  JS_FreeValue(ctx, buffer);

  fn = JS_GetPropertyStr(ctx, controller, "enqueue");
  ret = JS_Call(ctx, fn, controller, 1, &chunk);
  JS_FreeValue(ctx, fn);
  JS_FreeValue(ctx, chunk);
  return ret;
}

/**
 * @brief      Wraps a stream-utils.h Reader as a ReadableStream, pulling
 *             chunk_size bytes at a time into a fresh ArrayBuffer per pull(),
 *             closing the stream on EOF. Takes ownership of `reader` (freed
 *             once the source is exhausted, cancelled, or errors). For use by
 *             other C modules that already hold a Reader (e.g. from
 *             reader_from_fd()); JS code gets the same capability through
 *             ReadableStream.fromReader() below.
 *
 * @param      ctx         The JSContext
 * @param[in]  reader      The reader (ownership transferred)
 * @param[in]  chunk_size  Bytes requested per pull(); 0 uses a 64KiB default
 *
 * @return     A new ReadableStream instance, or JS_EXCEPTION
 */
JSValue
js_readable_stream_from_reader(JSContext* ctx, Reader reader, size_t chunk_size) {
  ReaderSource* rs;
  JSValue pull_fn, source, args[1], stream;

  if(JS_IsUndefined(readable_stream_ctor)) {
    reader_free(&reader);
    return JS_ThrowInternalError(ctx, "stream module not initialized");
  }

  if(!(rs = js_mallocz(ctx, sizeof(ReaderSource)))) {
    reader_free(&reader);
    return JS_EXCEPTION;
  }

  rs->reader = reader;
  rs->chunk_size = chunk_size ? chunk_size : 65536;

  pull_fn = js_function_cclosure(ctx, reader_source_pull, 1, 0, rs, reader_source_finalizer);

  source = JS_NewObject(ctx);
  JS_SetPropertyStr(ctx, source, "pull", pull_fn);

  args[0] = source;
  stream = JS_CallConstructor(ctx, readable_stream_ctor, 1, args);
  JS_FreeValue(ctx, source);
  return stream;
}

/* ReadableStream.fromReader(source, chunkSize): dispatches `source` through
 * reader_from_jsbuf/jsfunction/jsmethod exactly like JsonParser's
 * constructor - a buffer, a pull function fn(buf,len)->bytesRead, or an
 * object exposing that as its read() method - then wraps the resulting
 * Reader via js_readable_stream_from_reader(). */
static JSValue
js_readable_stream_from_reader_ctor(JSContext* ctx, JSValueConst this_val, int argc, JSValueConst argv[]) {
  JSValueConst input = argc > 0 ? argv[0] : JS_UNDEFINED;
  Reader reader;
  int64_t chunk_size = 0;

  if(argc > 1 && JS_ToInt64(ctx, &chunk_size, argv[1]))
    return JS_EXCEPTION;

  if(JS_IsFunction(ctx, input)) {
    reader = reader_from_jsfunction(ctx, input);
  } else if(JS_IsObject(input)) {
    JSValue read_fn = JS_GetPropertyStr(ctx, input, "read");

    if(JS_IsException(read_fn))
      return JS_EXCEPTION;

    if(JS_IsFunction(ctx, read_fn))
      reader = reader_from_jsmethod(ctx, read_fn, input);
    else
      reader = reader_from_jsbuf(ctx, input);

    JS_FreeValue(ctx, read_fn);
  } else {
    reader = reader_from_jsbuf(ctx, input);
  }

  return js_readable_stream_from_reader(ctx, reader, chunk_size > 0 ? (size_t)chunk_size : 0);
}

int
js_stream_init(JSContext* ctx, JSModuleDef* m) {
  static const char* const names[] = {
      "ReadableStream",
      "WritableStream",
      "TransformStream",
      "CountQueuingStrategy",
      "ByteLengthQueuingStrategy",
  };
  JSValue factory, exports, readable;
  size_t i;

  factory = JS_Eval(ctx, js_stream_src, strlen(js_stream_src), "<stream>", JS_EVAL_TYPE_GLOBAL);
  if(JS_IsException(factory))
    return -1;

  exports = JS_Call(ctx, factory, JS_UNDEFINED, 0, 0);
  JS_FreeValue(ctx, factory);
  if(JS_IsException(exports))
    return -1;

  readable = JS_GetPropertyStr(ctx, exports, "ReadableStream");
  JS_FreeValue(ctx, readable_stream_ctor);
  readable_stream_ctor = JS_DupValue(ctx, readable);
  JS_SetPropertyStr(ctx, readable, "fromReader", JS_NewCFunction(ctx, js_readable_stream_from_reader_ctor, "fromReader", 2));
  JS_FreeValue(ctx, readable);

  for(i = 0; i < countof(names); i++) {
    JSValue v = JS_GetPropertyStr(ctx, exports, names[i]);

    if(m)
      JS_SetModuleExport(ctx, m, names[i], v);
    else
      JS_FreeValue(ctx, v);
  }

  JS_FreeValue(ctx, exports);
  return 0;
}

#ifdef JS_SHARED_LIBRARY
#define JS_INIT_MODULE js_init_module
#else
#define JS_INIT_MODULE js_init_module_stream
#endif

VISIBLE JSModuleDef*
JS_INIT_MODULE(JSContext* ctx, const char* module_name) {
  JSModuleDef* m;
  static const char* const names[] = {
      "ReadableStream",
      "WritableStream",
      "TransformStream",
      "CountQueuingStrategy",
      "ByteLengthQueuingStrategy",
  };
  size_t i;

  if(!(m = JS_NewCModule(ctx, module_name, js_stream_init)))
    return NULL;

  for(i = 0; i < countof(names); i++)
    JS_AddModuleExport(ctx, m, names[i]);

  return m;
}

/**
 * @}
 */
